server:
  port: ${PORT:8081}
spring:
  application:
    name: route-picking-3opt-mid
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

reco:
  max-products: 10
  failure-rate: 0.10
  max-sweeps: 1000       
  max-improvements: 5000 
